HM7.1
Otus-DevOps-2023-09/AlexanderMokhovSer_infra pull request #16
Opened 2023-11-08 16:37 UTC by AlexanderMokhovSer

# Выполнено ДЗ № 7

2023-11-08 20:08 UTC, mrgreyves requested changes
Здравствуйте!)
Кажется что-то пошло не так с переменной db_ip 
Постарайтесь разобраться

2023-11-08 20:15 UTC, AlexanderMokhovSer commented
> Здравствуйте!) Кажется что-то пошло не так с переменной db_ip Постарайтесь разобраться

Вот не получается. Можете подсказать направление?

2023-11-08 21:06 UTC, AlexanderMokhovSer commented
> Здравствуйте!) Кажется что-то пошло не так с переменной db_ip Постарайтесь разобраться

Проверил еще раз - все необходимые переменные заданы в модулях (в том числе)

2023-11-10 14:31 UTC, mrgreyves approved these changes
Здравствуйте!)
Кажется что у вас все получилось поправить =)

2023-11-10 16:53 UTC, merged